### ISSUE TITLE
Not clickable with Firefox 60 (Mac)

### ISSUE THREAD

**Issue by cgpro** [zoxon/jquery-tabs#1]
Also in the demo:
https://zoxon.github.io/jquery-tabs/

**Comment by zoxon** [comment]
Hi, thank you for contributing.
This repository is obsolete. You can fix this issue by yourself. I think problem is [here](https://github.com/zoxon/jquery-tabs/blob/master/jquery.tabs.js#L102), tabs activates on `focus` in chrome but not in firefox.
Also you can use [vanilla javascript version of this plugin](https://github.com/zoxon/gulp-front/blob/master/source/modules/tabs/tabs.js).

**Comment by cgpro** [comment]
Thank you! Works now in FF ;-)
